name: pharma_app2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^3.1.0
  animations: ^1.1.2
  cached_network_image: ^2.5.0
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  device_preview: ^0.5.5
  dio: ^3.0.10
  equatable: ^1.2.5
  expandable: ^4.1.4
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.3
  # flutter_google_maps: ^4.0.0
  font_awesome_flutter: ^8.11.0
  geolocator: ^6.1.13
  get_it: ^5.0.3
  google_fonts: ^1.1.1
  image_picker: ^0.6.7+17
  injectable: ^1.0.5
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  jwt_decoder: ^1.0.4
  lint: ^1.3.0
  # location: ^3.2.1
  logger: ^0.9.4
  percent_indicator: ^2.1.9+1
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  sensors: ">=0.4.2+6 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  injectable_generator: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
